### ISSUE TITLE
[V2] Milestone 1 - Collapsed View

### ISSUE THREAD

**Issue by jribbink** [onflow/fcl-discovery#193]
This tracks milestone #1 of the V2 discovery update **collapsed view**.  This encompasses work to implement the mobile/small screen view of the Figma design.

- Filtering will _not_ be included in this iteration.  It was identified as lower priority and will be addressed later.
- The current task list encompasses all of the work on this milestone (excluding any UI touchups at the end)

Target:
<img width="421" alt="Screenshot 2024-07-11 at 9 04 40 AM" src="https://github.com/onflow/fcl-discovery/assets/17958158/44b8f5c1-e741-4cfb-aa9b-e519426ee4af">

https://www.figma.com/design/UoYdoIJCVYkaI74QKAAuZg/FLOW-FCL---UI-revamp-2024?node-id=2-35&t=gFd8gpYLh0xrHxtJ-0

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/fcl-discovery/issues/195
- [ ] https://github.com/onflow/fcl-discovery/issues/166
- [ ] https://github.com/onflow/fcl-discovery/issues/191
- [ ] https://github.com/onflow/fcl-discovery/issues/188
- [ ] https://github.com/onflow/fcl-discovery/issues/196
- [ ] https://github.com/onflow/fcl-discovery/issues/200
- [ ] https://github.com/onflow/fcl-discovery/issues/201
- [ ] https://github.com/onflow/fcl-discovery/issues/202
```
