### ISSUE TITLE
[V2] Milestone 2 - UI Completeness

### ISSUE THREAD

**Issue by jribbink** [onflow/fcl-discovery#210]
This milestone tracks UI completeness of the FCL Discovery revamp.  Previous milestone: https://github.com/onflow/fcl-discovery/issues/193

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/fcl-discovery/issues/156
- [ ] https://github.com/onflow/fcl-discovery/issues/211
- [ ] https://github.com/onflow/fcl-discovery/issues/212
- [ ] https://github.com/onflow/fcl-discovery/issues/214
- [ ] https://github.com/onflow/fcl-discovery/issues/215
- [ ] https://github.com/onflow/fcl-discovery/issues/217
- [ ] https://github.com/onflow/fcl-discovery/issues/222
- [ ] https://github.com/onflow/fcl-discovery/issues/225
- [ ] https://github.com/onflow/fcl-discovery/issues/226
- [ ] https://github.com/onflow/fcl-discovery/issues/227
- [ ] https://github.com/onflow/fcl-discovery/issues/228
- [ ] https://github.com/onflow/fcl-discovery/issues/232
- [ ] https://github.com/onflow/fcl-discovery/issues/233
- [ ] https://github.com/onflow/fcl-discovery/issues/235
- [ ] https://github.com/onflow/fcl-discovery/issues/240
```
