### ISSUE TITLE
Add event tracking

### ISSUE THREAD

**Issue by chasefleming** [onflow/fcl-discovery#48]
- [x] Track how many API requests are being made
- [x] Differentiate between UI vs API requests
- [x] Differentiate between networks
